apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-patroni
  namespace: his-masterdb
spec:
  replicas: 3
  serviceName: postgres-patroni
  selector:
    matchLabels:
      app: postgres-patroni
  template:
    metadata:
      labels:
        app: postgres-patroni
    spec:
      serviceAccountName: patroni                       # Use Patroni ServiceAccount here
      containers:
      - name: patroni
        image: registry.opensource.zalan.do/acid/spilo-15:3.0-p1
        ports:
        - containerPort: 10003
          name: postgres
        - containerPort: 8008
          name: patroni
        env:
        - name: SCOPE
          value: postgres-cluster
        - name: PGVERSION
          value: "15"
        - name: PGPORT
          value: "10003"
        - name: ETCD3_HOSTS
          value: 'etcd-0.etcd.his-masterdb.svc.cluster.local:2379,etcd-1.etcd.his-masterdb.svc.cluster.local:2379,etcd-2.etcd.his-masterdb.svc.cluster.local:2379'
        - name: KUBERNETES_SCOPE_LABEL
          value: app
        - name: KUBERNETES_ROLE_LABEL
          value: role
        - name: KUBERNETES_USE_CONFIGMAPS
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PGUSER_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: PGUSER_REPLICATOR
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: REPLICATION_USER
        - name: PGPASSWORD_REPLICATOR
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: REPLICATION_PASSWORD
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-data
          mountPath: /home/postgres/pgdata/pgroot
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: his-masterdb-local-path
      resources:
        requests:
          storage: 20Gi
