apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: postgres-ha
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.9
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: http://$(ETCD_NAME).etcd.postgres-ha.svc.cluster.local:2380
        - name: ETCD_LISTEN_PEER_URLS
          value: http://0.0.0.0:2380
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://$(ETCD_NAME).etcd.postgres-ha.svc.cluster.local:2379
        - name: ETCD_INITIAL_CLUSTER
          value: etcd-0=http://etcd-0.etcd.postgres-ha.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.postgres-ha.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd.postgres-ha.svc.cluster.local:2380
        - name: ETCD_INITIAL_CLUSTER_STATE
          value: new
        - name: ETCD_INITIAL_CLUSTER_TOKEN
          value: etcd-cluster
        - name: ETCD_DATA_DIR
          value: /var/lib/etcd
        volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: postgres-local-path
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: postgres-ha
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: etcd

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":["/home/alien/masterdb"]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-patroni
  namespace: postgres-ha
spec:
  serviceName: postgres-patroni
  replicas: 3
  selector:
    matchLabels:
      app: postgres-patroni
  template:
    metadata:
      labels:
        app: postgres-patroni
    spec:
      containers:
      - name: patroni
        image: registry.opensource.zalan.do/acid/spilo-15:3.0-p1
        ports:
        - containerPort: 10003
          name: postgres
        - containerPort: 8008
          name: patroni
        env:
        - name: SCOPE
          value: postgres-cluster
        - name: PGVERSION
          value: "15"
        - name: PGPORT
          value: "10003"
        - name: ETCD3_HOSTS
          value: 'etcd-0.etcd.postgres-ha.svc.cluster.local:2379,etcd-1.etcd.postgres-ha.svc.cluster.local:2379,etcd-2.etcd.postgres-ha.svc.cluster.local:2379'
        - name: KUBERNETES_LABELS
          value: '{app: postgres-patroni}'
        - name: KUBERNETES_SCOPE_LABEL
          value: app
        - name: KUBERNETES_ROLE_LABEL
          value: role
        - name: KUBERNETES_USE_CONFIGMAPS
          value: "true"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PGUSER_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: PGUSER_REPLICATOR
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: REPLICATION_USER
        - name: PGPASSWORD_REPLICATOR
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: REPLICATION_PASSWORD
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB
        - name: PATRONI_POSTGRESQL_CONNECT_ADDRESS
          value: '$(POD_IP):10003'
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:10003'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
        - name: PATRONI_BOOTSTRAP_DCS_POSTGRESQL_PARAMETERS_PORT
          value: "10003"
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-data
          mountPath: /home/postgres/pgdata
        - name: dshm
          mountPath: /dev/shm
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8008
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: postgres-local-path
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-ha
data:
  PATRONI_POSTGRESQL_PG_HBA: |
    host all all 0.0.0.0/0 trust
    host replication replicator 0.0.0.0/0 trust

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-patroni
  namespace: postgres-ha
spec:
  clusterIP: None
  ports:
  - port: 10003
    targetPort: 10003
    name: postgres
  - port: 8008
    name: patroni
  selector:
    app: postgres-patroni

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  namespace: postgres-ha
  labels:
    app: postgres-patroni
spec:
  type: NodePort
  ports:
  - port: 10003
    targetPort: 10003
    nodePort: 30002
    protocol: TCP
    name: postgres
  selector:
    app: postgres-patroni
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
  namespace: postgres-ha
  labels:
    app: postgres-patroni
spec:
  type: NodePort
  ports:
  - port: 10003
    targetPort: 10003
    nodePort: 30003
    protocol: TCP
    name: postgres
  selector:
    app: postgres-patroni
    role: replica

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-ha

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres-ha
type: Opaque
stringData:
  POSTGRES_USER: his
  POSTGRES_PASSWORD: his123
  POSTGRES_DB: registration
  REPLICATION_USER: replicator
  REPLICATION_PASSWORD: rep-pass

---
