apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres-ha
type: Opaque
stringData:
  POSTGRES_USER: his
  POSTGRES_PASSWORD: his123
  POSTGRES_DB: registration
  REPLICATION_USER: replicator
  REPLICATION_PASSWORD: rep-pass
