apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  namespace: his-masterdb
  labels:
    app: postgres-patroni
    role: master
spec:
  type: NodePort
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    nodePort: 30002
  selector:
    app: postgres-patroni
    role: master

