apiVersion: v1
kind: Service
metadata:
  name: postgres-patroni
  namespace: postgres-ha
spec:
  clusterIP: None
  ports:
  - port: 10003
    targetPort: 10003
    name: postgres
  - port: 8008
    name: patroni
  selector:
    app: postgres-patroni
