apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
  namespace: his-masterdb
  labels:
    app: postgres-patroni
spec:
  type: NodePort
  ports:
  - port: 10003
    targetPort: 10003
    nodePort: 30003
    protocol: TCP
    name: postgres
  selector:
    app: postgres-patroni
    role: replica
