apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-patroni
  namespace: his-masterdb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-patroni
subjects:
- kind: ServiceAccount
  name: postgres-patroni
  namespace: his-masterdb
