apiVersion: v1
kind: Service
metadata:
  name: postgres-patroni
  namespace: his-masterdb
  labels:
    app: postgres-patroni
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  - name: patroni
    port: 8008
    targetPort: 8008
  selector:
    app: postgres-patroni
