apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-patroni
  namespace: his-masterdb
  labels:
    app: postgres-patroni
spec:
  serviceName: postgres-patroni
  replicas: 3
  selector:
    matchLabels:
      app: postgres-patroni
  template:
    metadata:
      labels:
        app: postgres-patroni
    spec:
      serviceAccountName: postgres-patroni
      containers:
      - name: patroni
        image: ghcr.io/zalando/spilo-16:3.2-p3  # ← Changed image
        ports:
        - containerPort: 5432
          name: postgresql
        - containerPort: 8008
          name: patroni
        env:
        - name: SCOPE
          value: postgres-cluster
        - name: PGVERSION
          value: "16"
        - name: ETCD3_HOSTS
          value: "etcd-0.etcd.his-masterdb.svc.cluster.local:2379,etcd-1.etcd.his-masterdb.svc.cluster.local:2379,etcd-2.etcd.his-masterdb.svc.cluster.local:2379"
        - name: KUBERNETES_NAMESPACE
          value: his-masterdb
        - name: KUBERNETES_LABELS
          value: "app=postgres-patroni"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /home/postgres/pgdata
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8008
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
      labels:
        app: postgres-patroni
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage-masterdb
      resources:
        requests:
          storage: 20Gi
