apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
  namespace: his-masterdb
  labels:
    app: postgres-patroni
    role: replica
spec:
  type: NodePort
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    nodePort: 30003
  selector:
    app: postgres-patroni
    role: replica
